### ISSUE TITLE
Create the Contribution Page

### ISSUE THREAD

**Issue by hambrientoapp** [hambrientoapp/hambrientoapp#30]
Create the Contribution Page:

- [x] Create a functional component inside the pages folder with the filename `Contribution.js`
- [x] Create a div element with the id `contribution`
- [ ] Create a jumbotron element using the package `react-bootstrap`
- [x] Add to the jumbotron element an `H1` title con the text `Contribution`
- [x] Add a`P` element with sample text

**Comment by schmitty890** [comment]
Looks awesome! I can look into this!

**Comment by hambrientoapp** [comment]
> Looks awesome! I can look into this!

🙏 please @schmitty890
