### ISSUE TITLE
Create Report Component

### ISSUE THREAD

**Issue by hambrientoapp** [hambrientoapp/hambrientoapp#31]
Create the Report Component:

- [ ] Import and use the package `react-bootstrap`
- [ ] Create a functional component within the components folder with the name `Report.js`
- [ ] Create a `div` element with the id `report`
- [ ] Create a `H1` element with the text `Report Here`
- [ ] Create a `P` element with sample text
- [ ] Create a `Button` element with the text `Report`

**Comment by macanrox** [comment]
Can I take this one?

**Comment by hambrientoapp** [comment]
> Can I take this one?

🙏 please @macanrox

**Comment by hambrientoapp** [comment]
🚀 PR #35
