### ISSUE TITLE
Create Evaluate Component

### ISSUE THREAD

**Issue by hambrientoapp** [hambrientoapp/hambrientoapp#32]
Create the Evaluate Component:

- [x] Import and use the package `react-bootstrap`
- [x] Create a functional component within the components folder with the name `Evaluate.js`
- [x] Create a `div` element with the id `evaluate`
- [x] Create a `H1` element with the text `Evaluate Here`
- [x] Create a `P` element with sample text
- [x] Create a `Button` element with the text `Evaluate`

**Comment by asp2809** [comment]
Hi, I would like to contribute to this issue.
Is there a specific design that you want?

**Comment by hambrientoapp** [comment]
> Hi, I would like to contribute to this issue.
> Is there a specific design that you want?

🙏 please, you are free to let your imagination fly @asp2809

**Comment by asp2809** [comment]
> > Hi, I would like to contribute to this issue.
> > Is there a specific design that you want?
> 
> 🙏 please, you are free to let your imagination fly @asp2809

I will try to make the design similar to what we have.

**Comment by asp2809** [comment]
I have made a PR for the issue. Please find it in the following link: #37 
Please feel free to comment if anything else needs to be changed in the component.

**Comment by hambrientoapp** [comment]
👍 thanks a lot @asp2809 
🚀 PR #37
