### ISSUE TITLE
Report Form

### ISSUE THREAD

**Issue by hambrientoapp** [hambrientoapp/hambrientoapp#43]
Create the form component for registering places with the following fields:

- [x] Create in the `src/components` folder a file calles `RegisterForm.js`
- [x] Import and use the `react-bootstrap` package
- [x] Create a `label` element with the text _Name of the place_ name
- [x] Create a text type `input` element with the attribute name and the _namePlace_ value
- [x] Create a `label` element with the _Category_ text
- [x] Create a checkbox type `input` element with the _burger_ value and the _Burger_ text
- [x] Create a checkbox type `input` element with the _pizza_ value and the _Pizza_ text
- [x] Create a checkbox type `input` element with the _sushi_ value and the _Sushi_ text
- [x] Create a checkbox type `input` element with the _mexican_ value and the _Mexican_ text
- [x] Create a `label` element with the _Address_ text
- [x] Create a text type `input` element with the attribute name and the _address_ value
- [x] Create a `label` element with the _Coordinates_ text
- [x] Create a number type `input` element with the name and placeholder attributes with _latitude_ and _Latitude_ values respectively
 - [x] Create a number type `input` element with the name and placeholder attributes with _longitude_ and _Longitude_ values respectively

\* _Each label and input(s) must be in the same form group_

**Comment by F9Uf** [comment]
Can i try do that?
