### ISSUE TITLE
readme.me corrections

### ISSUE THREAD

**Issue by dondogecl** [hambrientoapp/hambrientoapp#65]
Hi. The readme.me file has some typos or simple mistakes, like "Direction" instead of "Address".
I suggest to edit the description and improve it.

**Comment by alemelomeza** [comment]
Thanks @dondogecl, can you `Fork` the project and request a `PR` with the corrections?

**Comment by alemelomeza** [comment]
I'm sorry, I saw that it's done 😅 thanks again @dondogecl
