### ISSUE TITLE
New categories needed (japanese food, chilean food)

### ISSUE THREAD

**Issue by dondogecl** [hambrientoapp/hambrientoapp#69]
Hi. I noticed that there is no Japanese or Chilean food in the categories.

**Comment by alemelomeza** [comment]
you are right, go ahead @dondogecl

**Comment by dondogecl** [comment]
Found some issues in Contador.js and Categories.js as well. Will fix them:
![image](https://user-images.githubusercontent.com/29621116/66938707-1133ce80-f018-11e9-812f-ec8eadb25159.png)

tags: bugs, Hactoberfest

**Comment by alemelomeza** [comment]
@dondogecl can you move the Japanese food category before the country categories ?

**Comment by dondogecl** [comment]
OK, I switched the icons for all countries, now they are using flags. @alemelomeza

**Comment by alemelomeza** [comment]
🚀 #71
